export const API_URL_USER = 'https://cinepacho-microservice-users-production.up.railway.app'
export const API_URL_MULTIPLEX = 'https://cinepacho-microservice-multiple-production.up.railway.app'
export const KEY_USER_TOKEN = 'USER_TOKEN'
export const KEY_CLIENT = 'CUSTOMERS_CLIENT'
export const KEY_CART_CONTENT = 'CART_CONTENT'