export const API_URL_USER = 'http://localhost:8090'
export const API_URL_MULTIPLEX = 'http://localhost:8091'
export const KEY_USER_TOKEN = 'USER_TOKEN'
export const KEY_CLIENT = 'CUSTOMERS_CLIENT'
export const KEY_CART_CONTENT = 'CART_CONTENT'